'use client'

import { createContext, useContext, useState, ReactNode } from 'react';

type Language = 'en' | 'hi' | 'bn';

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: 'Dashboard', history: 'History', addTransaction: 'Add Transaction', budgets: 'Budgets',
    insights: 'Insights', reports: 'Reports', settings: 'Settings', totalBalance: 'Total Balance',
    thisMonth: 'This Month', income: 'Income', expense: 'Expense', quickActions: 'Quick Actions',
    voice: 'Voice', scan: 'Scan', manual: 'Manual', import: 'Import', auto: 'Auto', pdf: 'PDF',
    pendingConfirmation: 'transactions pending confirmation', weeklyActivity: 'Weekly Activity',
    recentTransactions: 'Recent Transactions', viewAll: 'View All', noTransactions: 'No transactions yet',
    startTracking: 'Start tracking your finances', text: 'Text', parseWithAI: 'Parse with AI',
    typeHere: 'Type something like: Spent 500 on lunch at cafe', listening: 'Listening...',
    tapToSpeak: 'Tap to speak', uploadReceipt: 'Upload Receipt or Statement',
    dragDrop: 'Drag & drop or click to upload', supportedFormats: 'JPG, PNG, WebP, HEIC, PDF (max 10MB)',
    analyzing: 'Analyzing document...', amount: 'Amount', type: 'Type', category: 'Category',
    description: 'Description', date: 'Date', save: 'Save', confirm: 'Confirm', edit: 'Edit',
    discard: 'Discard', confirmAll: 'Confirm All', lowConfidence: 'Low confidence. Please review.',
    confidence: 'Confidence', all: 'All', confirmed: 'Confirmed', draft: 'Draft', search: 'Search',
    fromDate: 'From Date', toDate: 'To Date', selected: 'selected', printSelected: 'Print Selected',
    deleteSelected: 'Delete Selected', printAll: 'Print All', noResults: 'No transactions found',
    transactionDetails: 'Transaction Details', source: 'Source', status: 'Status', delete: 'Delete',
    print: 'Print', deleteConfirmTitle: 'Delete Transaction',
    deleteConfirmMessage: 'Are you sure? This cannot be undone.', cancel: 'Cancel',
    createBudget: 'Create Budget', budgetAmount: 'Budget Amount', period: 'Period', weekly: 'Weekly',
    monthly: 'Monthly', create: 'Create', spent: 'Spent', remaining: 'Remaining', used: 'used',
    noBudgets: 'No budgets yet', createFirst: 'Create a budget to track spending',
    budgetExists: 'Budget already exists', generateInsights: 'Generate Insights',
    analyzingFinances: 'Analyzing your finances...', lastGenerated: 'Last generated',
    insightsRemaining: 'insights remaining', resetsIn: 'resets in', noInsightsYet: 'No insights yet',
    clickGenerate: 'Click to get AI-powered insights', needMoreData: 'Need more transaction data',
    monthlyReports: 'Monthly Reports', viewDetails: 'View Details', totalIncome: 'Total Income',
    totalExpense: 'Total Expense', netSavings: 'Net Savings', categoryBreakdown: 'Category Breakdown',
    comparedToLast: 'Compared to last month', moreSpent: 'more spent', lessSpent: 'less spent',
    generateSummary: 'Generate AI Summary', noReports: 'No reports yet',
    addTransactionsFirst: 'Add transactions to see reports', profile: 'Profile', name: 'Name',
    email: 'Email', language: 'Language', english: 'English', hindi: 'Hindi', bengali: 'Bengali',
    notifications: 'Notifications', budgetAlerts: 'Budget Alerts', monthlyReportsNotif: 'Monthly Reports',
    backup: 'Backup', exportData: 'Export Data', restore: 'Restore', importData: 'Import Data',
    dangerZone: 'Danger Zone', deleteAllData: 'Delete All Data',
    deleteAllConfirm: 'This will delete all data. Cannot be undone.', about: 'About',
    privacyPolicy: 'Privacy Policy', termsOfService: 'Terms of Service', support: 'Support',
    version: 'Version', loading: 'Loading...', error: 'Error', success: 'Success', close: 'Close',
    back: 'Back', next: 'Next', previous: 'Previous', today: 'Today', yesterday: 'Yesterday',
    transactionSaved: 'Transaction saved', transactionDeleted: 'Transaction deleted',
    transactionConfirmed: 'Transaction confirmed', budgetCreated: 'Budget created',
    budgetDeleted: 'Budget deleted', dataExported: 'Data exported', dataImported: 'Data imported',
    dataDeleted: 'All data deleted', insightsGenerated: 'Insights generated',
    errorOccurred: 'An error occurred', logout: 'Logout', add: 'Add',
    incomeThisMonth: 'Income this month', expenseThisMonth: 'Expense this month',
    savingsRate: 'Savings Rate',

    // Dashboard
    currentBalance: 'Current Balance', allTime: 'All Time',
    saving: 'Saving', thisMonthInsight: 'This Month Insight', allTimeInsight: 'All Time Insight',
    youSpentXSoFar: 'You spent {amount} so far',
    weeklyActivityDesc: 'Income and expenses over the last 7 days',
    expenseBreakdown: 'Expense Breakdown',
    thisMonthByCategory: 'This month by category', allTimeByCategory: 'All time by category',

    // History
    download: 'Download', exportCSV: 'Export as CSV (.csv)', exportPDF: 'Export as PDF (.pdf)',
    selectAll: 'Select All', deleteX: 'Delete {count}', applyFilter: 'Apply Filter',
    clear: 'Clear', from: 'From', to: 'To', deleteTransactions: 'Delete Transactions?',
    deleteTransactionsConfirm: 'Are you sure you want to delete {count} transaction(s)? This cannot be undone.',
    yesDelete: 'Yes, Delete {count}', xTransactionsDeleted: '{count} transaction(s) deleted',

    // Budgets
    onTrack: 'On Track', nearLimit: 'Near Limit', overBudget: 'Over Budget',
    totalSpent: 'Total spent', spentSoFar: 'Spent so far',
    xOver: '{amount} over', xUsed: '{pct}% used',
    budgetLabel: 'Budget', overspendLabel: 'Overspend',
    totalBudget: 'Total budget', activeBudgets: 'Active budgets',
    allBudgets: 'All budgets', viewOnly: 'View Only',
    budgetLeft: 'Left', budgetOverBy: 'Over by',
    categoriesOverBudget: '{count} categories are over budget',
    considerAdjusting: 'Consider adjusting your limits or reducing spending',
    noBudgetsForMonth: 'No budgets for {month}',
    createBudgetToTrack: 'Create a budget to track your spending and stay on top of your finances.',
    editBudget: 'Edit Budget', updateSpendingLimit: 'Update your spending limit',
    budgetCategory: 'Category', budgetMonth: 'Month',
    savingEllipsis: 'Saving...', creatingEllipsis: 'Creating...',
    saveChanges: 'Save Changes', deleteBudgetTitle: 'Delete Budget?',
    deleteBudgetConfirm: 'Delete {category} budget for {month}? This cannot be undone.',
    budgetUpdatedSuccess: 'Budget updated successfully!',
    budgetCreatedSuccess: 'Budget created successfully!',
    budgetDeletedToast: 'Budget deleted',
    somethingWentWrong: 'Something went wrong',

    // Insights
    aiPoweredAnalysis: 'AI-powered analysis of your last 30 days',
    transactionsAnalysed: '{count} transactions analysed',
    analysingEllipsis: 'Analysing...',
    readingTransactions: 'Reading your transactions...',
    identifyingPatterns: 'Identifying spending patterns...',
    comparingCategories: 'Comparing categories...',
    writingInsights: 'Writing your insights...',
    almostDone: 'Almost done...',
    noInsightsDescription: 'Generate AI insights to understand your spending patterns',
    aiDisclaimer: 'AI-generated insights may not always be accurate. Always verify with a financial advisor before making major decisions.',
    learnMore: 'Learn More',

    // Reports
    reportsAutoGenerated: 'Your financial reports are generated automatically on the 1st of each month',
    noReportsYetDesc: 'Your first report will be automatically generated on 1st {month} {year}',
    generated: 'Generated', downloadBtn: 'Download',
    reportDownloaded: 'Report downloaded!', downloadFailed: 'Download failed. Try again.',
    reportsInfoBanner: 'Reports are automatically generated on the 1st of each month and include your complete financial summary with AI-powered insights.',

    // Settings
    managePreferences: 'Manage your preferences',
    installFinFlowApp: 'Install FinFlow App',
    homeScreenQuickAccess: 'Add to home screen for quick access',
    installBtn: 'Install',
    emailNotifications: 'EMAIL NOTIFICATIONS',
    monthlyReport: 'Monthly Report',
    monthlyReportDesc: 'Receive monthly summary by email',
    budgetAlertsDesc: 'Get notified when budget limit is near',
    tipsGuidance: 'Tips & Guidance',
    tipsGuidanceDesc: 'Receive helpful tips and guidance by email',
    pushNotifications: 'PUSH NOTIFICATIONS',
    browserPushNotifications: 'Browser Push Notifications',
    browserPushDesc: 'Receive alerts even when app is closed',
    enablePushToConfigure: 'Enable push notifications to configure alerts below',
    pushBudgetAlertsDesc: 'Notify when spending reaches 80% of budget',
    largeTransactions: 'Large Transactions',
    largeTransactionsDesc: 'Alert for transactions above ₹10,000',
    dailySummary: 'Daily Summary',
    dailySummaryDesc: 'Daily spending digest',
    inAppNotificationsLabel: 'IN-APP NOTIFICATIONS',
    inAppNotifications: 'In-App Notifications',
    inAppDesc: 'Show notification bell icon alerts',
    enableInAppToConfigure: 'Enable in-app notifications to configure alerts below',
    inAppBudgetAlertsDesc: 'In-app alert when budget limit is near',
    inAppLargeTxDesc: 'In-app alert for transactions above ₹10,000',
    inAppDailySummaryDesc: 'Daily spending digest in-app',
    dangerZoneLabel: 'DANGER ZONE',
    dangerZoneDesc: 'Permanently deletes all transactions, budgets, categories, and settings. Cannot be undone.',
    deleteAllDataBtn: 'Delete All Data',
    deleteAllDataTitle: 'Delete All Data?',
    followingWillBeDeleted: 'The following will be permanently deleted:',
    allTransactionsEntries: 'All transactions & entries',
    budgetSettingsLimits: 'Budget settings & limits',
    categoriesCustomTags: 'Categories & custom tags',
    allPreferencesSettings: 'All preferences & settings',
    actionPermanent: 'This action is permanent and cannot be undone.',
    iUnderstandContinue: 'I understand, continue →',
    confirmDeletion: 'Confirm Deletion',
    typeDeleteToConfirm: 'Type {delete} to confirm',
    typeDeletePlaceholder: 'Type DELETE to confirm',
    mustTypeDeleteExactly: 'Must type DELETE exactly',
    deletingEllipsis: 'Deleting...',
    allDataDeletedSuccess: 'All data deleted successfully',
    tryAgain: 'Please try again.',
    failedEnablePush: 'Failed to enable push notifications',

    // Profile
    uploadingEllipsis: 'Uploading...',
    memberSince: 'Member since {date}',
    entries: 'Entries', streak: 'Streak', spentLabel: 'Spent',
    account: 'Account', cannotBeChanged: '(cannot be changed)',
    changeBtn: 'Change',
    integrations: 'Integrations',
    telegramConnected: 'Telegram Connected', connectTelegram: 'Connect Telegram',
    addTxViaTelegram: 'Add transactions via Telegram bot',
    openTelegramSearchBot: 'Open Telegram and search @FinFlowBot',
    sendStartGetChatId: 'Send /start to get your Chat ID',
    enterChatIdBelow: 'Enter your Chat ID below',
    enterTelegramChatId: 'Enter your Telegram Chat ID',
    connectBtn: 'Connect',
    connectingEllipsis: 'Connecting...',
    waitingWhatsAppConfirm: 'Waiting for WhatsApp confirmation',
    whatsappConnected: 'WhatsApp Connected', connectWhatsApp: 'Connect WhatsApp',
    addTxViaWhatsApp: 'Add transactions via WhatsApp',
    usage: 'Usage',
    aiUsageThisMonth: 'AI Usage This Month',
    xUsedPct: '{pct}% used',
    resetsOn1st: 'Resets on 1st of next month',
    loadingUsage: 'Loading usage...',
    preferences: 'Preferences',
    notificationsNav: 'Notifications', privacySecurityNav: 'Privacy & Security',
    dataBackupRestore: 'Data Backup & Restore',
    helpSupport: 'Help & Support',
    feedbackNav: 'Feedback',
    versionLabel: 'Version',
    privacyPolicyNav: 'Privacy Policy', termsOfServiceNav: 'Terms of Service',
    disclaimer: 'Disclaimer',
    signOut: 'Sign Out',
    signOutTitle: 'Sign Out?',
    signOutDesc: "You'll need to sign in again to access your account.",
    selectLanguage: 'Select Language',
    feedbackTitle: 'Feedback',
    feedbackDesc: 'Share your thoughts, report a bug, or suggest a feature.',
    writeFeedbackPlaceholder: 'Write your feedback here...',
    feedbackRateLimit: "You've reached the feedback limit (3 per 24 hours). Please try again later.",
    feedbackError: 'Something went wrong. Please try again.',
    submittingEllipsis: 'Submitting...',
    submitFeedback: 'Submit Feedback',
    thankYou: 'Thank you!',
    feedbackSubmitted: 'Your feedback has been submitted.',
    closeBtn: 'Close',
    disconnectTelegramTitle: 'Disconnect Telegram?',
    disconnectTelegramDesc: "You won't receive transactions on Telegram.",
    disconnectBtn: 'Disconnect',
    disconnectWhatsAppTitle: 'Disconnect WhatsApp?',
    disconnectWhatsAppDesc: "You won't receive transactions on WhatsApp.",
    failedConnect: 'Failed to connect. Please try again.',
    failedGenerateCode: 'Failed to generate connect code',
    whatsappConnectedSuccess: 'WhatsApp connected successfully!',
    connectionTimedOut: 'Connection timed out. Please try again.',
    whatsappDisconnected: 'WhatsApp disconnected',
    failedDisconnect: 'Failed to disconnect. Please try again.',

    // Notifications
    notificationsTitle: 'Notifications',
    searchNotifications: 'Search notifications...',
    unread: 'Unread',
    markAllAsRead: 'Mark all as read',
    selectMessages: 'Select messages',
    selectAllNotifs: 'Select all',
    cancelSelection: 'Cancel selection',
    noMatchingNotifications: 'No matching notifications',
    noUnreadNotifications: 'No unread notifications',
    noNotificationsYet: 'No notifications yet',
    tryAdjustingSearch: 'Try adjusting your search',
    allCaughtUp: "You're all caught up!",
    notifyWhenSomethingHappens: "We'll notify you when something happens.",
    clearSearch: 'Clear search',
    deselectAll: 'Deselect all',
    xSelected: '{count} selected',
    markRead: 'Mark read',
    deleteXNotifs: 'Delete ({count})',
    notificationDeleted: 'Notification deleted',
    failedDeleteNotification: 'Failed to delete notification',
    allNotifsMarkedRead: 'All notifications marked as read',
    xNotifsDeleted: '{count} notification(s) deleted',
    failedDeleteSomeNotifs: 'Failed to delete some notifications',
    xNotifsMarkedRead: '{count} notification(s) marked as read',
    loadMore: 'Load more',
    loadingMore: 'Loading...',

    // Privacy & Security
    privacySecurityTitle: 'Privacy & Security',
    accountSecurity: 'ACCOUNT SECURITY',
    changePassword: 'Change Password',
    updateAccountPassword: 'Update your account password',
    currentPassword: 'Current Password',
    enterCurrentPassword: 'Enter current password',
    currentPasswordRequired: 'Current password is required',
    newPassword: 'New Password',
    minCharacters: 'Min. 8 characters',
    weak: 'Weak', medium: 'Medium', strong: 'Strong',
    atLeast8Chars: 'At least 8 characters',
    containsNumber: 'Contains a number',
    containsSpecialChar: 'Contains a special character (!@#$%^&*)',
    confirmNewPassword: 'Confirm New Password',
    repeatNewPassword: 'Repeat new password',
    passwordsMatch: 'Passwords match',
    passwordsNoMatch: 'Passwords do not match',
    updatingEllipsis: 'Updating...',
    passwordUpdated: 'Password Updated!',
    updatePassword: 'Update Password',
    passwordUpdatedSuccess: 'Password updated successfully!',
    unableToVerifyAccount: 'Unable to verify your account. Please log in again.',
    currentPasswordIncorrect: 'Current password is incorrect.',
    dataAnalytics: 'DATA & ANALYTICS',
    analyticsCrashReports: 'Analytics & Crash Reports',
    shareAnonymousData: 'Share anonymous usage data to improve FinFlow',
    neverSellData: 'We never sell your data. Analytics are fully anonymous and contain no personal or financial information.',

    // Backup & Restore
    backupRestoreTitle: 'Backup & Restore',
    backupYourData: 'Backup Your Data',
    exportCopyForSafekeeping: 'Export a copy of your data for safekeeping. You can restore it at any time using the Restore section below.',
    exportingEllipsis: 'Exporting...',
    downloaded: 'Downloaded!',
    exportCSVBtn: 'Export CSV',
    txBudgetsAsSpreadsheet: 'Transactions & budgets as spreadsheet',
    exportJSONBtn: 'Export JSON',
    txBudgetsAsJSON: 'Transactions & budgets as JSON file',
    restoreData: 'Restore Data',
    importMayOverwrite: 'Importing data may overwrite your existing records. We recommend exporting a backup first.',
    dropBackupFile: 'Drop your backup file here',
    supportsCSVJSON: 'Supports .csv and .json files',
    browseFile: 'Browse File',
    fileReadyToImport: 'File ready to import',
    changeBtnLabel: 'Change',
    transactionsFound: 'Transactions found',
    dateRange: 'Date range',
    budgetsLabel: 'Budgets',
    categoriesLabel: 'Categories',
    importMode: 'Import Mode',
    merge: 'Merge',
    addToExistingData: 'Add to existing data',
    replace: 'Replace',
    overwriteAllData: 'Overwrite all data',
    willDeleteCurrentData: 'This will delete all your current data',
    importingEllipsis: 'Importing...',
    mergeImportData: 'Merge & Import Data',
    replaceImportData: 'Replace & Import Data',
    noTxToExport: 'No transactions to export.',
    exportFailedTryAgain: 'Export failed, try again.',
    fileTooLarge: 'File too large. Maximum size is 5MB.',
    onlyJsonCSVSupported: 'Only .json and .csv files are supported.',
    noValidDataInFile: 'No valid data found in file.',
    invalidFile: 'Invalid file. Please use a FinFlow export.',
    dataImportedSuccess: 'Data imported successfully ({count} transaction(s) added)',
    importFailed: 'Import failed. Please check your file format.',

    // Transaction Detail
    noteOptional: 'Note (optional)',
    addANote: 'Add a note...',
    timeLabel: 'Time',
    noteLabel: 'Note',

    // Add - ManualTab
    allCategories: 'All Categories',
    morePlus: 'More +',
    whatWasThisFor: 'What was this for? (optional)',
    savingTransaction: 'Saving...',
    saveTransaction: 'Save Transaction',
    pleaseEnterAmount: 'Please enter an amount',
    pleaseSelectCategory: 'Please select a category',

    // Add - NLPTab
    xTransactionsFound: '{count} transactions found',
    discardAll: 'Discard all',
    saveAllX: 'Save All ({count})',
    nlpPlaceholder: 'e.g. "Spent 2000 on food and 290 on transport"',
    parsingEllipsis: 'Parsing...',
    parseWithAI: 'Parse with AI',
    failedToParse: 'Failed to parse. Please try again.',

    // Add - VoiceTab
    voiceCaptured: 'Voice captured',
    processingEllipsis: 'Processing...',
    listeningStatus: 'Listening...',
    tapToSpeakStatus: 'Tap to speak',
    voiceLanguages: 'Hindi · Bengali · Tamil · Telugu & more',
    micAccessDenied: 'Microphone access denied. Please allow access and try again.',
    couldNotCatch: "Couldn't catch that. Please tap and try again.",
    transcriptLabel: 'Transcript:',

    // Add - ScanTab
    readingImage: 'Reading image...',
    extractingText: 'Extracting text...',
    parsingDetails: 'Parsing details...',
    doneLabel: 'Done!',
    openCamera: 'Open Camera',
    uploadFromGallery: 'Upload from Gallery',
    jpgPngPdfSupported: 'JPG, PNG, PDF supported',
    scanningEllipsis: 'Scanning...',
    failedToScan: 'Failed to scan receipt',

    // PreviewCard
    aiUnderstoodAs: 'AI understood this as:',
    aiConfidence: 'AI Confidence',
    pleaseVerifyDetails: 'Please verify details',
    confirmSave: 'Confirm Save',

    // Layout
    addBtn: 'Add',
    viewProfile: 'View Profile',
    editProfile: 'Edit Profile',
    signOutBtn: 'Sign Out',
    printedOn: 'Printed on {date}',

    // NotificationCenter
    notifHeader: 'Notifications',
    noNotifsYet: 'No notifications yet',
    markAllRead: 'Mark All as Read',
    viewAllNotifs: 'View All',

    // InstallPrompt
    installPromptTitle: 'Install FinFlow',
    tapShareAddToHome: 'Tap Share then "Add to Home Screen"',
    addToHomeQuickAccess: 'Add to home screen for quick access',
    installPromptBtn: 'Install',
  },
  hi: {
    dashboard: 'डैशबोर्ड', history: 'इतिहास', addTransaction: 'लेनदेन जोड़ें', budgets: 'बजट',
    insights: 'अंतर्दृष्टि', reports: 'रिपोर्ट', settings: 'सेटिंग्स', totalBalance: 'कुल शेष',
    thisMonth: 'इस महीने', income: 'आय', expense: 'व्यय', quickActions: 'त्वरित कार्य',
    voice: 'वॉयस', scan: 'स्कैन', manual: 'मैनुअल', import: 'आयात', auto: 'ऑटो', pdf: 'PDF',
    pendingConfirmation: 'लेनदेन पुष्टि के लिए', weeklyActivity: 'साप्ताहिक गतिविधि',
    recentTransactions: 'हाल के लेनदेन', viewAll: 'सभी देखें', noTransactions: 'कोई लेनदेन नहीं',
    startTracking: 'अपने वित्त को ट्रैक करें', text: 'टेक्स्ट', parseWithAI: 'AI से पार्स करें',
    typeHere: 'टाइप करें: कैफे में 500 खर्च किए', listening: 'सुन रहा हूं...',
    tapToSpeak: 'बोलने के लिए टैप करें', uploadReceipt: 'रसीद अपलोड करें',
    dragDrop: 'ड्रैग या क्लिक करें', supportedFormats: 'JPG, PNG, PDF (10MB तक)',
    analyzing: 'विश्लेषण हो रहा है...', amount: 'राशि', type: 'प्रकार', category: 'श्रेणी',
    description: 'विवरण', date: 'तारीख', save: 'सहेजें', confirm: 'पुष्टि करें', edit: 'संपादित करें',
    discard: 'रद्द करें', confirmAll: 'सभी पुष्टि करें', lowConfidence: 'कम विश्वास।',
    confidence: 'विश्वास', all: 'सभी', confirmed: 'पुष्टि', draft: 'ड्राफ्ट', search: 'खोजें',
    fromDate: 'से तारीख', toDate: 'तक तारीख', selected: 'चयनित', printSelected: 'प्रिंट करें',
    deleteSelected: 'हटाएं', printAll: 'सभी प्रिंट', noResults: 'कोई लेनदेन नहीं',
    transactionDetails: 'लेनदेन विवरण', source: 'स्रोत', status: 'स्थिति', delete: 'हटाएं',
    print: 'प्रिंट', deleteConfirmTitle: 'लेनदेन हटाएं',
    deleteConfirmMessage: 'क्या आप निश्चित हैं?', cancel: 'रद्द करें',
    createBudget: 'बजट बनाएं', budgetAmount: 'बजट राशि', period: 'अवधि', weekly: 'साप्ताहिक',
    monthly: 'मासिक', create: 'बनाएं', spent: 'खर्च', remaining: 'शेष', used: 'उपयोग',
    noBudgets: 'कोई बजट नहीं', createFirst: 'बजट बनाएं',
    budgetExists: 'बजट पहले से है', generateInsights: 'अंतर्दृष्टि बनाएं',
    analyzingFinances: 'विश्लेषण हो रहा है...', lastGenerated: 'अंतिम',
    insightsRemaining: 'शेष', resetsIn: 'रीसेट', noInsightsYet: 'कोई अंतर्दृष्टि नहीं',
    clickGenerate: 'AI अंतर्दृष्टि के लिए क्लिक करें', needMoreData: 'अधिक डेटा चाहिए',
    monthlyReports: 'मासिक रिपोर्ट', viewDetails: 'विवरण देखें', totalIncome: 'कुल आय',
    totalExpense: 'कुल व्यय', netSavings: 'शुद्ध बचत', categoryBreakdown: 'श्रेणी विवरण',
    comparedToLast: 'पिछले महीने से', moreSpent: 'अधिक खर्च', lessSpent: 'कम खर्च',
    generateSummary: 'AI सारांश', noReports: 'कोई रिपोर्ट नहीं',
    addTransactionsFirst: 'रिपोर्ट के लिए लेनदेन जोड़ें', profile: 'प्रोफ़ाइल', name: 'नाम',
    email: 'ईमेल', language: 'भाषा', english: 'अंग्रेज़ी', hindi: 'हिंदी', bengali: 'बंगाली',
    notifications: 'सूचनाएं', budgetAlerts: 'बजट अलर्ट', monthlyReportsNotif: 'मासिक रिपोर्ट',
    backup: 'बैकअप', exportData: 'निर्यात करें', restore: 'पुनर्स्थापित', importData: 'आयात करें',
    dangerZone: 'खतरा क्षेत्र', deleteAllData: 'सब हटाएं',
    deleteAllConfirm: 'यह सब कुछ हटा देगा।', about: 'बारे में',
    privacyPolicy: 'गोपनीयता नीति', termsOfService: 'सेवा शर्तें', support: 'सहायता',
    version: 'संस्करण', loading: 'लोड हो रहा...', error: 'त्रुटि', success: 'सफल', close: 'बंद',
    back: 'वापस', next: 'अगला', previous: 'पिछला', today: 'आज', yesterday: 'कल',
    transactionSaved: 'लेनदेन सहेजा', transactionDeleted: 'लेनदेन हटाया',
    transactionConfirmed: 'लेनदेन पुष्टि', budgetCreated: 'बजट बनाया',
    budgetDeleted: 'बजट हटाया', dataExported: 'निर्यात हुआ', dataImported: 'आयात हुआ',
    dataDeleted: 'सब हटाया', insightsGenerated: 'अंतर्दृष्टि बनी',
    errorOccurred: 'त्रुटि हुई', logout: 'लॉगआउट', add: 'जोड़ें',
    incomeThisMonth: 'इस महीने की आय', expenseThisMonth: 'इस महीने का खर्च',
    savingsRate: 'बचत दर',

    // Dashboard
    currentBalance: 'वर्तमान शेष', allTime: 'सभी समय',
    saving: 'बचत', thisMonthInsight: 'इस महीने की जानकारी', allTimeInsight: 'सभी समय की जानकारी',
    youSpentXSoFar: 'आपने अब तक {amount} खर्च किया',
    weeklyActivityDesc: 'पिछले 7 दिनों की आय और व्यय',
    expenseBreakdown: 'व्यय विवरण',
    thisMonthByCategory: 'इस महीने श्रेणी अनुसार', allTimeByCategory: 'सभी समय श्रेणी अनुसार',

    // History
    download: 'डाउनलोड', exportCSV: 'CSV निर्यात (.csv)', exportPDF: 'PDF निर्यात (.pdf)',
    selectAll: 'सभी चुनें', deleteX: '{count} हटाएं', applyFilter: 'फ़िल्टर लागू करें',
    clear: 'साफ़ करें', from: 'से', to: 'तक', deleteTransactions: 'लेनदेन हटाएं?',
    deleteTransactionsConfirm: 'क्या आप {count} लेनदेन हटाना चाहते हैं? यह वापस नहीं होगा।',
    yesDelete: 'हाँ, {count} हटाएं', xTransactionsDeleted: '{count} लेनदेन हटाए गए',

    // Budgets
    onTrack: 'सही रास्ते पर', nearLimit: 'सीमा के पास', overBudget: 'बजट से अधिक',
    totalSpent: 'कुल खर्च', spentSoFar: 'अब तक खर्च',
    xOver: '{amount} अधिक', xUsed: '{pct}% उपयोग',
    budgetLabel: 'बजट', overspendLabel: 'अतिव्यय',
    totalBudget: 'कुल बजट', activeBudgets: 'सक्रिय बजट',
    allBudgets: 'सभी बजट', viewOnly: 'केवल देखें',
    budgetLeft: 'शेष', budgetOverBy: 'अधिक',
    categoriesOverBudget: '{count} श्रेणियां बजट से अधिक हैं',
    considerAdjusting: 'अपनी सीमाएं समायोजित करें या खर्च कम करें',
    noBudgetsForMonth: '{month} के लिए कोई बजट नहीं',
    createBudgetToTrack: 'अपने खर्च को ट्रैक करने के लिए बजट बनाएं।',
    editBudget: 'बजट संपादित करें', updateSpendingLimit: 'अपनी खर्च सीमा अपडेट करें',
    budgetCategory: 'श्रेणी', budgetMonth: 'महीना',
    savingEllipsis: 'सहेज रहा है...', creatingEllipsis: 'बना रहा है...',
    saveChanges: 'परिवर्तन सहेजें', deleteBudgetTitle: 'बजट हटाएं?',
    deleteBudgetConfirm: '{month} के लिए {category} बजट हटाएं? यह वापस नहीं होगा।',
    budgetUpdatedSuccess: 'बजट अपडेट हुआ!',
    budgetCreatedSuccess: 'बजट बनाया गया!',
    budgetDeletedToast: 'बजट हटाया गया',
    somethingWentWrong: 'कुछ गलत हो गया',

    // Insights
    aiPoweredAnalysis: 'पिछले 30 दिनों का AI विश्लेषण',
    transactionsAnalysed: '{count} लेनदेन विश्लेषित',
    analysingEllipsis: 'विश्लेषण हो रहा है...',
    readingTransactions: 'लेनदेन पढ़ रहा है...',
    identifyingPatterns: 'खर्च पैटर्न पहचान रहा है...',
    comparingCategories: 'श्रेणियों की तुलना कर रहा है...',
    writingInsights: 'अंतर्दृष्टि लिख रहा है...',
    almostDone: 'लगभग हो गया...',
    noInsightsDescription: 'अपने खर्च पैटर्न समझने के लिए AI अंतर्दृष्टि बनाएं',
    aiDisclaimer: 'AI-जनित अंतर्दृष्टि हमेशा सटीक नहीं हो सकती। बड़े निर्णयों से पहले वित्तीय सलाहकार से सत्यापित करें।',
    learnMore: 'और जानें',

    // Reports
    reportsAutoGenerated: 'आपकी वित्तीय रिपोर्ट हर महीने की 1 तारीख को स्वतः बनती है',
    noReportsYetDesc: 'आपकी पहली रिपोर्ट {month} {year} की 1 तारीख को बनेगी',
    generated: 'बनाई गई', downloadBtn: 'डाउनलोड',
    reportDownloaded: 'रिपोर्ट डाउनलोड हुई!', downloadFailed: 'डाउनलोड विफल। पुनः प्रयास करें।',
    reportsInfoBanner: 'रिपोर्ट हर महीने की 1 तारीख को स्वतः बनती है और AI-संचालित अंतर्दृष्टि के साथ पूर्ण वित्तीय सारांश शामिल करती है।',

    // Settings
    managePreferences: 'अपनी प्राथमिकताएं प्रबंधित करें',
    installFinFlowApp: 'FinFlow ऐप इंस्टॉल करें',
    homeScreenQuickAccess: 'त्वरित पहुंच के लिए होम स्क्रीन पर जोड़ें',
    installBtn: 'इंस्टॉल',
    emailNotifications: 'ईमेल सूचनाएं',
    monthlyReport: 'मासिक रिपोर्ट',
    monthlyReportDesc: 'ईमेल द्वारा मासिक सारांश प्राप्त करें',
    budgetAlertsDesc: 'बजट सीमा के पास होने पर सूचित करें',
    tipsGuidance: 'सुझाव और मार्गदर्शन',
    tipsGuidanceDesc: 'ईमेल द्वारा उपयोगी सुझाव प्राप्त करें',
    pushNotifications: 'पुश सूचनाएं',
    browserPushNotifications: 'ब्राउज़र पुश सूचनाएं',
    browserPushDesc: 'ऐप बंद होने पर भी अलर्ट प्राप्त करें',
    enablePushToConfigure: 'नीचे अलर्ट कॉन्फ़िगर करने के लिए पुश सूचनाएं सक्षम करें',
    pushBudgetAlertsDesc: 'बजट का 80% खर्च होने पर सूचित करें',
    largeTransactions: 'बड़े लेनदेन',
    largeTransactionsDesc: '₹10,000 से अधिक लेनदेन पर अलर्ट',
    dailySummary: 'दैनिक सारांश',
    dailySummaryDesc: 'दैनिक खर्च सारांश',
    inAppNotificationsLabel: 'इन-ऐप सूचनाएं',
    inAppNotifications: 'इन-ऐप सूचनाएं',
    inAppDesc: 'नोटिफिकेशन बेल आइकन अलर्ट दिखाएं',
    enableInAppToConfigure: 'नीचे अलर्ट कॉन्फ़िगर करने के लिए इन-ऐप सूचनाएं सक्षम करें',
    inAppBudgetAlertsDesc: 'बजट सीमा के पास होने पर इन-ऐप अलर्ट',
    inAppLargeTxDesc: '₹10,000 से अधिक लेनदेन पर इन-ऐप अलर्ट',
    inAppDailySummaryDesc: 'इन-ऐप दैनिक खर्च सारांश',
    dangerZoneLabel: 'खतरा क्षेत्र',
    dangerZoneDesc: 'सभी लेनदेन, बजट, श्रेणियां और सेटिंग्स स्थायी रूप से हटा देता है। वापस नहीं हो सकता।',
    deleteAllDataBtn: 'सभी डेटा हटाएं',
    deleteAllDataTitle: 'सभी डेटा हटाएं?',
    followingWillBeDeleted: 'निम्नलिखित स्थायी रूप से हटा दिया जाएगा:',
    allTransactionsEntries: 'सभी लेनदेन और प्रविष्टियां',
    budgetSettingsLimits: 'बजट सेटिंग्स और सीमाएं',
    categoriesCustomTags: 'श्रेणियां और कस्टम टैग',
    allPreferencesSettings: 'सभी प्राथमिकताएं और सेटिंग्स',
    actionPermanent: 'यह कार्रवाई स्थायी है और वापस नहीं हो सकती।',
    iUnderstandContinue: 'मैं समझता हूं, जारी रखें →',
    confirmDeletion: 'हटाने की पुष्टि करें',
    typeDeleteToConfirm: 'पुष्टि के लिए {delete} टाइप करें',
    typeDeletePlaceholder: 'पुष्टि के लिए DELETE टाइप करें',
    mustTypeDeleteExactly: 'DELETE ठीक से टाइप करें',
    deletingEllipsis: 'हटा रहा है...',
    allDataDeletedSuccess: 'सभी डेटा सफलतापूर्वक हटाया गया',
    tryAgain: 'कृपया पुनः प्रयास करें।',
    failedEnablePush: 'पुश सूचनाएं सक्षम करने में विफल',

    // Profile
    uploadingEllipsis: 'अपलोड हो रहा है...',
    memberSince: '{date} से सदस्य',
    entries: 'प्रविष्टियां', streak: 'स्ट्रीक', spentLabel: 'खर्च',
    account: 'खाता', cannotBeChanged: '(बदल नहीं सकते)',
    changeBtn: 'बदलें',
    integrations: 'इंटीग्रेशन',
    telegramConnected: 'टेलीग्राम जुड़ा है', connectTelegram: 'टेलीग्राम जोड़ें',
    addTxViaTelegram: 'टेलीग्राम बॉट से लेनदेन जोड़ें',
    openTelegramSearchBot: 'टेलीग्राम खोलें और @FinFlowBot खोजें',
    sendStartGetChatId: 'Chat ID प्राप्त करने के लिए /start भेजें',
    enterChatIdBelow: 'नीचे अपना Chat ID दर्ज करें',
    enterTelegramChatId: 'अपना टेलीग्राम Chat ID दर्ज करें',
    connectBtn: 'जोड़ें',
    connectingEllipsis: 'जुड़ रहा है...',
    waitingWhatsAppConfirm: 'WhatsApp पुष्टि की प्रतीक्षा',
    whatsappConnected: 'WhatsApp जुड़ा है', connectWhatsApp: 'WhatsApp जोड़ें',
    addTxViaWhatsApp: 'WhatsApp से लेनदेन जोड़ें',
    usage: 'उपयोग',
    aiUsageThisMonth: 'इस महीने AI उपयोग',
    xUsedPct: '{pct}% उपयोग',
    resetsOn1st: 'अगले महीने की 1 तारीख को रीसेट',
    loadingUsage: 'उपयोग लोड हो रहा है...',
    preferences: 'प्राथमिकताएं',
    notificationsNav: 'सूचनाएं', privacySecurityNav: 'गोपनीयता और सुरक्षा',
    dataBackupRestore: 'डेटा बैकअप और रिस्टोर',
    helpSupport: 'सहायता',
    feedbackNav: 'प्रतिक्रिया',
    versionLabel: 'संस्करण',
    privacyPolicyNav: 'गोपनीयता नीति', termsOfServiceNav: 'सेवा शर्तें',
    disclaimer: 'अस्वीकरण',
    signOut: 'साइन आउट',
    signOutTitle: 'साइन आउट?',
    signOutDesc: 'अपने खाते तक पहुंचने के लिए आपको फिर से साइन इन करना होगा।',
    selectLanguage: 'भाषा चुनें',
    feedbackTitle: 'प्रतिक्रिया',
    feedbackDesc: 'अपने विचार साझा करें, बग रिपोर्ट करें, या सुविधा सुझाएं।',
    writeFeedbackPlaceholder: 'यहां अपनी प्रतिक्रिया लिखें...',
    feedbackRateLimit: 'आपने प्रतिक्रिया सीमा (24 घंटे में 3) पूरी कर ली है। बाद में पुनः प्रयास करें।',
    feedbackError: 'कुछ गलत हो गया। कृपया पुनः प्रयास करें।',
    submittingEllipsis: 'जमा हो रहा है...',
    submitFeedback: 'प्रतिक्रिया जमा करें',
    thankYou: 'धन्यवाद!',
    feedbackSubmitted: 'आपकी प्रतिक्रिया जमा हो गई है।',
    closeBtn: 'बंद',
    disconnectTelegramTitle: 'टेलीग्राम डिस्कनेक्ट करें?',
    disconnectTelegramDesc: 'आपको टेलीग्राम पर लेनदेन प्राप्त नहीं होंगे।',
    disconnectBtn: 'डिस्कनेक्ट',
    disconnectWhatsAppTitle: 'WhatsApp डिस्कनेक्ट करें?',
    disconnectWhatsAppDesc: 'आपको WhatsApp पर लेनदेन प्राप्त नहीं होंगे।',
    failedConnect: 'कनेक्ट करने में विफल। पुनः प्रयास करें।',
    failedGenerateCode: 'कनेक्ट कोड बनाने में विफल',
    whatsappConnectedSuccess: 'WhatsApp सफलतापूर्वक जुड़ गया!',
    connectionTimedOut: 'कनेक्शन टाइम आउट। पुनः प्रयास करें।',
    whatsappDisconnected: 'WhatsApp डिस्कनेक्ट हुआ',
    failedDisconnect: 'डिस्कनेक्ट करने में विफल। पुनः प्रयास करें।',

    // Notifications
    notificationsTitle: 'सूचनाएं',
    searchNotifications: 'सूचनाएं खोजें...',
    unread: 'अपठित',
    markAllAsRead: 'सभी पठित चिह्नित करें',
    selectMessages: 'संदेश चुनें',
    selectAllNotifs: 'सभी चुनें',
    cancelSelection: 'चयन रद्द करें',
    noMatchingNotifications: 'कोई मेल खाती सूचना नहीं',
    noUnreadNotifications: 'कोई अपठित सूचना नहीं',
    noNotificationsYet: 'अभी कोई सूचना नहीं',
    tryAdjustingSearch: 'अपनी खोज समायोजित करें',
    allCaughtUp: 'आप सब पढ़ चुके हैं!',
    notifyWhenSomethingHappens: 'कुछ होने पर हम आपको सूचित करेंगे।',
    clearSearch: 'खोज साफ़ करें',
    deselectAll: 'सभी अचयनित',
    xSelected: '{count} चयनित',
    markRead: 'पठित चिह्नित करें',
    deleteXNotifs: 'हटाएं ({count})',
    notificationDeleted: 'सूचना हटाई गई',
    failedDeleteNotification: 'सूचना हटाने में विफल',
    allNotifsMarkedRead: 'सभी सूचनाएं पठित चिह्नित',
    xNotifsDeleted: '{count} सूचनाएं हटाई गईं',
    failedDeleteSomeNotifs: 'कुछ सूचनाएं हटाने में विफल',
    xNotifsMarkedRead: '{count} सूचनाएं पठित चिह्नित',
    loadMore: 'और लोड करें',
    loadingMore: 'लोड हो रहा है...',

    // Privacy & Security
    privacySecurityTitle: 'गोपनीयता और सुरक्षा',
    accountSecurity: 'खाता सुरक्षा',
    changePassword: 'पासवर्ड बदलें',
    updateAccountPassword: 'अपना खाता पासवर्ड अपडेट करें',
    currentPassword: 'वर्तमान पासवर्ड',
    enterCurrentPassword: 'वर्तमान पासवर्ड दर्ज करें',
    currentPasswordRequired: 'वर्तमान पासवर्ड आवश्यक है',
    newPassword: 'नया पासवर्ड',
    minCharacters: 'कम से कम 8 अक्षर',
    weak: 'कमज़ोर', medium: 'मध्यम', strong: 'मज़बूत',
    atLeast8Chars: 'कम से कम 8 अक्षर',
    containsNumber: 'एक अंक शामिल है',
    containsSpecialChar: 'एक विशेष अक्षर शामिल है (!@#$%^&*)',
    confirmNewPassword: 'नया पासवर्ड पुष्टि करें',
    repeatNewPassword: 'नया पासवर्ड दोहराएं',
    passwordsMatch: 'पासवर्ड मेल खाते हैं',
    passwordsNoMatch: 'पासवर्ड मेल नहीं खाते',
    updatingEllipsis: 'अपडेट हो रहा है...',
    passwordUpdated: 'पासवर्ड अपडेट हुआ!',
    updatePassword: 'पासवर्ड अपडेट करें',
    passwordUpdatedSuccess: 'पासवर्ड सफलतापूर्वक अपडेट हुआ!',
    unableToVerifyAccount: 'आपका खाता सत्यापित नहीं हो सका। कृपया फिर से लॉग इन करें।',
    currentPasswordIncorrect: 'वर्तमान पासवर्ड गलत है।',
    dataAnalytics: 'डेटा और एनालिटिक्स',
    analyticsCrashReports: 'एनालिटिक्स और क्रैश रिपोर्ट',
    shareAnonymousData: 'FinFlow सुधारने के लिए गुमनाम उपयोग डेटा साझा करें',
    neverSellData: 'हम आपका डेटा कभी नहीं बेचते। एनालिटिक्स पूरी तरह गुमनाम है।',

    // Backup & Restore
    backupRestoreTitle: 'बैकअप और रिस्टोर',
    backupYourData: 'अपना डेटा बैकअप करें',
    exportCopyForSafekeeping: 'सुरक्षित रखने के लिए अपने डेटा की कॉपी निर्यात करें।',
    exportingEllipsis: 'निर्यात हो रहा है...',
    downloaded: 'डाउनलोड हुआ!',
    exportCSVBtn: 'CSV निर्यात',
    txBudgetsAsSpreadsheet: 'स्प्रेडशीट के रूप में लेनदेन और बजट',
    exportJSONBtn: 'JSON निर्यात',
    txBudgetsAsJSON: 'JSON फ़ाइल के रूप में लेनदेन और बजट',
    restoreData: 'डेटा रिस्टोर करें',
    importMayOverwrite: 'डेटा आयात करने से मौजूदा रिकॉर्ड ओवरराइट हो सकते हैं।',
    dropBackupFile: 'अपनी बैकअप फ़ाइल यहां डालें',
    supportsCSVJSON: '.csv और .json फ़ाइलें समर्थित',
    browseFile: 'फ़ाइल ब्राउज़ करें',
    fileReadyToImport: 'आयात के लिए फ़ाइल तैयार',
    changeBtnLabel: 'बदलें',
    transactionsFound: 'लेनदेन मिले',
    dateRange: 'तारीख सीमा',
    budgetsLabel: 'बजट',
    categoriesLabel: 'श्रेणियां',
    importMode: 'आयात मोड',
    merge: 'मर्ज',
    addToExistingData: 'मौजूदा डेटा में जोड़ें',
    replace: 'बदलें',
    overwriteAllData: 'सभी डेटा ओवरराइट करें',
    willDeleteCurrentData: 'यह आपका मौजूदा डेटा हटा देगा',
    importingEllipsis: 'आयात हो रहा है...',
    mergeImportData: 'मर्ज और आयात करें',
    replaceImportData: 'बदलें और आयात करें',
    noTxToExport: 'निर्यात करने के लिए कोई लेनदेन नहीं।',
    exportFailedTryAgain: 'निर्यात विफल। पुनः प्रयास करें।',
    fileTooLarge: 'फ़ाइल बहुत बड़ी है। अधिकतम आकार 5MB है।',
    onlyJsonCSVSupported: 'केवल .json और .csv फ़ाइलें समर्थित।',
    noValidDataInFile: 'फ़ाइल में कोई मान्य डेटा नहीं।',
    invalidFile: 'अमान्य फ़ाइल। कृपया FinFlow निर्यात उपयोग करें।',
    dataImportedSuccess: 'डेटा सफलतापूर्वक आयात हुआ ({count} लेनदेन जोड़े गए)',
    importFailed: 'आयात विफल। कृपया अपनी फ़ाइल फ़ॉर्मेट जांचें।',

    // Transaction Detail
    noteOptional: 'नोट (वैकल्पिक)',
    addANote: 'नोट जोड़ें...',
    timeLabel: 'समय',
    noteLabel: 'नोट',

    // Add - ManualTab
    allCategories: 'सभी श्रेणियां',
    morePlus: 'और +',
    whatWasThisFor: 'यह किसके लिए था? (वैकल्पिक)',
    savingTransaction: 'सहेज रहा है...',
    saveTransaction: 'लेनदेन सहेजें',
    pleaseEnterAmount: 'कृपया राशि दर्ज करें',
    pleaseSelectCategory: 'कृपया श्रेणी चुनें',

    // Add - NLPTab
    xTransactionsFound: '{count} लेनदेन मिले',
    discardAll: 'सभी रद्द करें',
    saveAllX: 'सभी सहेजें ({count})',
    nlpPlaceholder: 'जैसे: "खाने पर 2000 और परिवहन पर 290 खर्च किए"',
    parsingEllipsis: 'पार्स हो रहा है...',
    parseWithAI: 'AI से पार्स करें',
    failedToParse: 'पार्स करने में विफल। पुनः प्रयास करें।',

    // Add - VoiceTab
    voiceCaptured: 'वॉयस कैप्चर हुआ',
    processingEllipsis: 'प्रोसेसिंग...',
    listeningStatus: 'सुन रहा है...',
    tapToSpeakStatus: 'बोलने के लिए टैप करें',
    voiceLanguages: 'हिंदी · बंगाली · तमिल · तेलुगु और अधिक',
    micAccessDenied: 'माइक्रोफोन एक्सेस अस्वीकृत। कृपया एक्सेस अनुमति दें।',
    couldNotCatch: 'सुन नहीं पाए। कृपया फिर से टैप करें।',
    transcriptLabel: 'ट्रांस्क्रिप्ट:',

    // Add - ScanTab
    readingImage: 'छवि पढ़ रहा है...',
    extractingText: 'टेक्स्ट निकाल रहा है...',
    parsingDetails: 'विवरण पार्स कर रहा है...',
    doneLabel: 'हो गया!',
    openCamera: 'कैमरा खोलें',
    uploadFromGallery: 'गैलरी से अपलोड करें',
    jpgPngPdfSupported: 'JPG, PNG, PDF समर्थित',
    scanningEllipsis: 'स्कैन हो रहा है...',
    failedToScan: 'रसीद स्कैन करने में विफल',

    // PreviewCard
    aiUnderstoodAs: 'AI ने यह समझा:',
    aiConfidence: 'AI विश्वास',
    pleaseVerifyDetails: 'कृपया विवरण सत्यापित करें',
    confirmSave: 'सहेजने की पुष्टि करें',

    // Layout
    addBtn: 'जोड़ें',
    viewProfile: 'प्रोफ़ाइल देखें',
    editProfile: 'प्रोफ़ाइल संपादित करें',
    signOutBtn: 'साइन आउट',
    printedOn: '{date} को प्रिंट किया गया',

    // NotificationCenter
    notifHeader: 'सूचनाएं',
    noNotifsYet: 'अभी कोई सूचना नहीं',
    markAllRead: 'सभी पठित चिह्नित करें',
    viewAllNotifs: 'सभी देखें',

    // InstallPrompt
    installPromptTitle: 'FinFlow इंस्टॉल करें',
    tapShareAddToHome: 'Share टैप करें फिर "होम स्क्रीन पर जोड़ें"',
    addToHomeQuickAccess: 'त्वरित पहुंच के लिए होम स्क्रीन पर जोड़ें',
    installPromptBtn: 'इंस्टॉल',
  },
  bn: {
    dashboard: 'ড্যাশবোর্ড', history: 'ইতিহাস', addTransaction: 'লেনদেন যোগ', budgets: 'বাজেট',
    insights: 'অন্তর্দৃষ্টি', reports: 'রিপোর্ট', settings: 'সেটিংস', totalBalance: 'মোট ব্যালেন্স',
    thisMonth: 'এই মাস', income: 'আয়', expense: 'ব্যয়', quickActions: 'দ্রুত ক্রিয়া',
    voice: 'ভয়েস', scan: 'স্ক্যান', manual: 'ম্যানুয়াল', import: 'আমদানি', auto: 'অটো', pdf: 'PDF',
    pendingConfirmation: 'লেনদেন মুলতুবি', weeklyActivity: 'সাপ্তাহিক কার্যকলাপ',
    recentTransactions: 'সাম্প্রতিক লেনদেন', viewAll: 'সব দেখুন', noTransactions: 'কোন লেনদেন নেই',
    startTracking: 'আর্থিক ট্র্যাক করুন', text: 'টেক্সট', parseWithAI: 'AI দিয়ে পার্স',
    typeHere: 'টাইপ করুন: ক্যাফেতে 500 খরচ', listening: 'শুনছি...',
    tapToSpeak: 'বলতে ট্যাপ করুন', uploadReceipt: 'রসিদ আপলোড',
    dragDrop: 'ড্র্যাগ বা ক্লিক করুন', supportedFormats: 'JPG, PNG, PDF (10MB)',
    analyzing: 'বিশ্লেষণ হচ্ছে...', amount: 'পরিমাণ', type: 'প্রকার', category: 'বিভাগ',
    description: 'বিবরণ', date: 'তারিখ', save: 'সংরক্ষণ', confirm: 'নিশ্চিত', edit: 'সম্পাদনা',
    discard: 'বাতিল', confirmAll: 'সব নিশ্চিত', lowConfidence: 'কম আস্থা।',
    confidence: 'আস্থা', all: 'সব', confirmed: 'নিশ্চিত', draft: 'খসড়া', search: 'অনুসন্ধান',
    fromDate: 'থেকে', toDate: 'পর্যন্ত', selected: 'নির্বাচিত', printSelected: 'প্রিন্ট',
    deleteSelected: 'মুছুন', printAll: 'সব প্রিন্ট', noResults: 'কোন লেনদেন নেই',
    transactionDetails: 'লেনদেন বিবরণ', source: 'উৎস', status: 'অবস্থা', delete: 'মুছুন',
    print: 'প্রিন্ট', deleteConfirmTitle: 'লেনদেন মুছুন',
    deleteConfirmMessage: 'আপনি কি নিশ্চিত?', cancel: 'বাতিল',
    createBudget: 'বাজেট তৈরি', budgetAmount: 'বাজেট পরিমাণ', period: 'সময়কাল', weekly: 'সাপ্তাহিক',
    monthly: 'মাসিক', create: 'তৈরি', spent: 'খরচ', remaining: 'অবশিষ্ট', used: 'ব্যবহৃত',
    noBudgets: 'কোন বাজেট নেই', createFirst: 'বাজেট তৈরি করুন',
    budgetExists: 'বাজেট আছে', generateInsights: 'অন্তর্দৃষ্টি তৈরি',
    analyzingFinances: 'বিশ্লেষণ হচ্ছে...', lastGenerated: 'শেষ',
    insightsRemaining: 'বাকি', resetsIn: 'রিসেট', noInsightsYet: 'কোন অন্তর্দৃষ্টি নেই',
    clickGenerate: 'AI অন্তর্দৃষ্টির জন্য ক্লিক', needMoreData: 'আরও ডেটা দরকার',
    monthlyReports: 'মাসিক রিপোর্ট', viewDetails: 'বিস্তারিত', totalIncome: 'মোট আয়',
    totalExpense: 'মোট ব্যয়', netSavings: 'নিট সঞ্চয়', categoryBreakdown: 'বিভাগ বিভাজন',
    comparedToLast: 'গত মাসের তুলনায়', moreSpent: 'বেশি খরচ', lessSpent: 'কম খরচ',
    generateSummary: 'AI সারাংশ', noReports: 'কোন রিপোর্ট নেই',
    addTransactionsFirst: 'রিপোর্টের জন্য লেনদেন যোগ করুন', profile: 'প্রোফাইল', name: 'নাম',
    email: 'ইমেল', language: 'ভাষা', english: 'ইংরেজি', hindi: 'হিন্দি', bengali: 'বাংলা',
    notifications: 'বিজ্ঞপ্তি', budgetAlerts: 'বাজেট সতর্কতা', monthlyReportsNotif: 'মাসিক রিপোর্ট',
    backup: 'ব্যাকআপ', exportData: 'রপ্তানি', restore: 'পুনরুদ্ধার', importData: 'আমদানি',
    dangerZone: 'বিপদ অঞ্চল', deleteAllData: 'সব মুছুন',
    deleteAllConfirm: 'এটি সব মুছে ফেলবে।', about: 'সম্পর্কে',
    privacyPolicy: 'গোপনীয়তা নীতি', termsOfService: 'সেবার শর্তাবলী', support: 'সহায়তা',
    version: 'সংস্করণ', loading: 'লোড হচ্ছে...', error: 'ত্রুটি', success: 'সফল', close: 'বন্ধ',
    back: 'পেছনে', next: 'পরবর্তী', previous: 'পূর্ববর্তী', today: 'আজ', yesterday: 'গতকাল',
    transactionSaved: 'লেনদেন সংরক্ষিত', transactionDeleted: 'লেনদেন মুছে ফেলা',
    transactionConfirmed: 'লেনদেন নিশ্চিত', budgetCreated: 'বাজেট তৈরি',
    budgetDeleted: 'বাজেট মুছে ফেলা', dataExported: 'রপ্তানি হয়েছে', dataImported: 'আমদানি হয়েছে',
    dataDeleted: 'সব মুছে ফেলা', insightsGenerated: 'অন্তর্দৃষ্টি তৈরি',
    errorOccurred: 'ত্রুটি ঘটেছে', logout: 'লগআউট', add: 'যোগ',
    incomeThisMonth: 'এই মাসের আয়', expenseThisMonth: 'এই মাসের খরচ',
    savingsRate: 'সঞ্চয় হার',

    // Dashboard
    currentBalance: 'বর্তমান ব্যালেন্স', allTime: 'সব সময়',
    saving: 'সঞ্চয়', thisMonthInsight: 'এই মাসের তথ্য', allTimeInsight: 'সব সময়ের তথ্য',
    youSpentXSoFar: 'আপনি এখন পর্যন্ত {amount} খর্চ করেছেন',
    weeklyActivityDesc: 'গত ৭ দিনের আয় ও ব্যয়',
    expenseBreakdown: 'ব্যয় বিশ্লেষণ',
    thisMonthByCategory: 'এই মাসে শ্রেণী অনুসারে', allTimeByCategory: 'সব সময় শ্রেণী অনুসারে',

    // History
    download: 'ডাউনলোড', exportCSV: 'CSV রপ্তানি (.csv)', exportPDF: 'PDF রপ্তানি (.pdf)',
    selectAll: 'সব নির্বাচন', deleteX: '{count} মুছুন', applyFilter: 'ফিল্টার প্রয়োগ',
    clear: 'মুছুন', from: 'থেকে', to: 'পর্যন্ত', deleteTransactions: 'লেনদেন মুছবেন?',
    deleteTransactionsConfirm: 'আপনি কি {count}টি লেনদেন মুছতে চান? এটি ফেরত যাবে না।',
    yesDelete: 'হ্যাঁ, {count} মুছুন', xTransactionsDeleted: '{count}টি লেনদেন মুছে ফেলা হয়েছে',

    // Budgets
    onTrack: 'সঠিক পথে', nearLimit: 'সীমার কাছে', overBudget: 'বাজেটের বেশি',
    totalSpent: 'মোট খরচ', spentSoFar: 'এখন পর্যন্ত খরচ',
    xOver: '{amount} বেশি', xUsed: '{pct}% ব্যবহৃত',
    budgetLabel: 'বাজেট', overspendLabel: 'অতিরিক্ত খরচ',
    totalBudget: 'মোট বাজেট', activeBudgets: 'সক্রিয় বাজেট',
    allBudgets: 'সব বাজেট', viewOnly: 'শুধু দেখুন',
    budgetLeft: 'বাকি', budgetOverBy: 'বেশি',
    categoriesOverBudget: '{count}টি শ্রেণী বাজেটের বেশি',
    considerAdjusting: 'আপনার সীমা সামঞ্জস্য করুন বা খরচ কমান',
    noBudgetsForMonth: '{month} মাসে কোনো বাজেট নেই',
    createBudgetToTrack: 'আপনার খরচ ট্র্যাক করতে একটি বাজেট তৈরি করুন।',
    editBudget: 'বাজেট সম্পাদনা', updateSpendingLimit: 'আপনার খরচের সীমা আপডেট করুন',
    budgetCategory: 'শ্রেণী', budgetMonth: 'মাস',
    savingEllipsis: 'সংরক্ষণ হচ্ছে...', creatingEllipsis: 'তৈরি হচ্ছে...',
    saveChanges: 'পরিবর্তন সংরক্ষণ', deleteBudgetTitle: 'বাজেট মুছবেন?',
    deleteBudgetConfirm: '{month} মাসের {category} বাজেট মুছবেন? এটি ফেরত যাবে না।',
    budgetUpdatedSuccess: 'বাজেট সফলভাবে আপডেট হয়েছে!',
    budgetCreatedSuccess: 'বাজেট সফলভাবে তৈরি হয়েছে!',
    budgetDeletedToast: 'বাজেট মুছে ফেলা হয়েছে',
    somethingWentWrong: 'কিছু সমস্যা হয়েছে',

    // Insights
    aiPoweredAnalysis: 'আপনার গত ৩০ দিনের AI-চালিত বিশ্লেষণ',
    transactionsAnalysed: '{count}টি লেনদেন বিশ্লেষিত',
    analysingEllipsis: 'বিশ্লেষণ হচ্ছে...',
    readingTransactions: 'আপনার লেনদেন পড়া হচ্ছে...',
    identifyingPatterns: 'খরচের প্যাটার্ন শনাক্ত করা হচ্ছে...',
    comparingCategories: 'শ্রেণী তুলনা করা হচ্ছে...',
    writingInsights: 'আপনার তথ্য লেখা হচ্ছে...',
    almostDone: 'প্রায় শেষ...',
    noInsightsDescription: 'আপনার খরচের প্যাটার্ন বুঝতে AI তথ্য তৈরি করুন',
    aiDisclaimer: 'AI-তৈরি তথ্য সবসময় সঠিক নাও হতে পারে। বড় সিদ্ধান্ত নেওয়ার আগে আর্থিক উপদেষ্টার সাথে যাচাই করুন।',
    learnMore: 'আরও জানুন',

    // Reports
    reportsAutoGenerated: 'আপনার আর্থিক রিপোর্ট প্রতি মাসের ১ তারিখে স্বয়ংক্রিয়ভাবে তৈরি হয়',
    noReportsYetDesc: 'আপনার প্রথম রিপোর্ট {month} {year}-এর ১ তারিখে স্বয়ংক্রিয়ভাবে তৈরি হবে',
    generated: 'তৈরি হয়েছে', downloadBtn: 'ডাউনলোড',
    reportDownloaded: 'রিপোর্ট ডাউনলোড হয়েছে!', downloadFailed: 'ডাউনলোড ব্যর্থ। আবার চেষ্টা করুন।',
    reportsInfoBanner: 'রিপোর্ট প্রতি মাসের ১ তারিখে স্বয়ংক্রিয়ভাবে তৈরি হয় এবং আপনার সম্পূর্ণ আর্থিক সারসংক্ষেপ ও AI-চালিত তথ্য অন্তর্ভুক্ত করে।',

    // Settings
    managePreferences: 'আপনার পছন্দসমূহ পরিচালনা করুন',
    installFinFlowApp: 'FinFlow অ্যাপ ইনস্টল করুন',
    homeScreenQuickAccess: 'দ্রুত অ্যাক্সেসের জন্য হোম স্ক্রিনে যোগ করুন',
    installBtn: 'ইনস্টল',
    emailNotifications: 'ইমেইল বিজ্ঞপ্তি',
    monthlyReport: 'মাসিক রিপোর্ট',
    monthlyReportDesc: 'ইমেইলে মাসিক সারসংক্ষেপ পান',
    budgetAlertsDesc: 'বাজেট সীমা কাছে এলে বিজ্ঞপ্তি পান',
    tipsGuidance: 'টিপস ও নির্দেশনা',
    tipsGuidanceDesc: 'ইমেইলে সহায়ক টিপস ও নির্দেশনা পান',
    pushNotifications: 'পুশ বিজ্ঞপ্তি',
    browserPushNotifications: 'ব্রাউজার পুশ বিজ্ঞপ্তি',
    browserPushDesc: 'অ্যাপ বন্ধ থাকলেও সতর্কতা পান',
    enablePushToConfigure: 'নীচের সতর্কতা কনফিগার করতে পুশ বিজ্ঞপ্তি চালু করুন',
    pushBudgetAlertsDesc: 'খরচ বাজেটের ৮০% পৌঁছালে জানান',
    largeTransactions: 'বড় লেনদেন',
    largeTransactionsDesc: '₹১০,০০০-এর বেশি লেনদেনের জন্য সতর্কতা',
    dailySummary: 'দৈনিক সারসংক্ষেপ',
    dailySummaryDesc: 'দৈনিক খরচের সারসংক্ষেপ',
    inAppNotificationsLabel: 'অ্যাপের মধ্যে বিজ্ঞপ্তি',
    inAppNotifications: 'অ্যাপের মধ্যে বিজ্ঞপ্তি',
    inAppDesc: 'বিজ্ঞপ্তি ঘণ্টা আইকন সতর্কতা দেখান',
    enableInAppToConfigure: 'নীচের সতর্কতা কনফিগার করতে অ্যাপের মধ্যে বিজ্ঞপ্তি চালু করুন',
    inAppBudgetAlertsDesc: 'বাজেট সীমা কাছে এলে অ্যাপের মধ্যে সতর্কতা',
    inAppLargeTxDesc: '₹১০,০০০-এর বেশি লেনদেনের জন্য অ্যাপের মধ্যে সতর্কতা',
    inAppDailySummaryDesc: 'অ্যাপের মধ্যে দৈনিক খরচের সারসংক্ষেপ',
    dangerZoneLabel: 'বিপদ অঞ্চল',
    dangerZoneDesc: 'সমস্ত লেনদেন, বাজেট, শ্রেণী এবং সেটিংস স্থায়ীভাবে মুছে ফেলে। ফেরত যাবে না।',
    deleteAllDataBtn: 'সব ডেটা মুছুন',
    deleteAllDataTitle: 'সব ডেটা মুছবেন?',
    followingWillBeDeleted: 'নিম্নলিখিত স্থায়ীভাবে মুছে ফেলা হবে:',
    allTransactionsEntries: 'সমস্ত লেনদেন ও এন্ট্রি',
    budgetSettingsLimits: 'বাজেট সেটিংস ও সীমা',
    categoriesCustomTags: 'শ্রেণী ও কাস্টম ট্যাগ',
    allPreferencesSettings: 'সমস্ত পছন্দ ও সেটিংস',
    actionPermanent: 'এই কাজ স্থায়ী এবং ফেরত যাবে না।',
    iUnderstandContinue: 'আমি বুঝেছি, এগিয়ে যান →',
    confirmDeletion: 'মুছে ফেলা নিশ্চিত করুন',
    typeDeleteToConfirm: 'নিশ্চিত করতে {delete} টাইপ করুন',
    typeDeletePlaceholder: 'নিশ্চিত করতে DELETE টাইপ করুন',
    mustTypeDeleteExactly: 'ঠিক DELETE টাইপ করতে হবে',
    deletingEllipsis: 'মুছে ফেলা হচ্ছে...',
    allDataDeletedSuccess: 'সব ডেটা সফলভাবে মুছে ফেলা হয়েছে',
    tryAgain: 'আবার চেষ্টা করুন।',
    failedEnablePush: 'পুশ বিজ্ঞপ্তি চালু করতে ব্যর্থ',

    // Profile
    uploadingEllipsis: 'আপলোড হচ্ছে...',
    memberSince: '{date} থেকে সদস্য',
    entries: 'এন্ট্রি', streak: 'ধারা', spentLabel: 'খরচ',
    account: 'অ্যাকাউন্ট', cannotBeChanged: '(পরিবর্তন করা যাবে না)',
    changeBtn: 'পরিবর্তন',
    integrations: 'ইন্টিগ্রেশন',
    telegramConnected: 'টেলিগ্রাম সংযুক্ত', connectTelegram: 'টেলিগ্রাম সংযুক্ত করুন',
    addTxViaTelegram: 'টেলিগ্রাম বটের মাধ্যমে লেনদেন যোগ করুন',
    openTelegramSearchBot: 'টেলিগ্রাম খুলে @FinFlowBot অনুসন্ধান করুন',
    sendStartGetChatId: 'আপনার চ্যাট আইডি পেতে /start পাঠান',
    enterChatIdBelow: 'নীচে আপনার চ্যাট আইডি দিন',
    enterTelegramChatId: 'আপনার টেলিগ্রাম চ্যাট আইডি দিন',
    connectBtn: 'সংযুক্ত করুন',
    connectingEllipsis: 'সংযুক্ত হচ্ছে...',
    waitingWhatsAppConfirm: 'হোয়াটসঅ্যাপ নিশ্চিতকরণের জন্য অপেক্ষা হচ্ছে',
    whatsappConnected: 'হোয়াটসঅ্যাপ সংযুক্ত', connectWhatsApp: 'হোয়াটসঅ্যাপ সংযুক্ত করুন',
    addTxViaWhatsApp: 'হোয়াটসঅ্যাপের মাধ্যমে লেনদেন যোগ করুন',
    usage: 'ব্যবহার',
    aiUsageThisMonth: 'এই মাসের AI ব্যবহার',
    xUsedPct: '{pct}% ব্যবহৃত',
    resetsOn1st: 'পরের মাসের ১ তারিখে রিসেট হবে',
    loadingUsage: 'ব্যবহার লোড হচ্ছে...',
    preferences: 'পছন্দসমূহ',
    notificationsNav: 'বিজ্ঞপ্তি', privacySecurityNav: 'গোপনীয়তা ও নিরাপত্তা',
    dataBackupRestore: 'ডেটা ব্যাকআপ ও পুনরুদ্ধার',
    helpSupport: 'সাহায্য ও সমর্থন',
    feedbackNav: 'মতামত',
    versionLabel: 'সংস্করণ',
    privacyPolicyNav: 'গোপনীয়তা নীতি', termsOfServiceNav: 'সেবার শর্তাবলী',
    disclaimer: 'দাবিত্যাগ',
    signOut: 'সাইন আউট',
    signOutTitle: 'সাইন আউট করবেন?',
    signOutDesc: 'আপনার অ্যাকাউন্টে প্রবেশ করতে আবার সাইন ইন করতে হবে।',
    selectLanguage: 'ভাষা নির্বাচন',
    feedbackTitle: 'মতামত',
    feedbackDesc: 'আপনার মতামত শেয়ার করুন, বাগ রিপোর্ট করুন বা ফিচার সাজেস্ট করুন।',
    writeFeedbackPlaceholder: 'এখানে আপনার মতামত লিখুন...',
    feedbackRateLimit: 'আপনি মতামতের সীমা (২৪ ঘণ্টায় ৩টি) পৌঁছেছেন। পরে আবার চেষ্টা করুন।',
    feedbackError: 'কিছু সমস্যা হয়েছে। আবার চেষ্টা করুন।',
    submittingEllipsis: 'জমা হচ্ছে...',
    submitFeedback: 'মতামত জমা দিন',
    thankYou: 'ধন্যবাদ!',
    feedbackSubmitted: 'আপনার মতামত জমা হয়েছে।',
    closeBtn: 'বন্ধ',
    disconnectTelegramTitle: 'টেলিগ্রাম সংযোগ বিচ্ছিন্ন করবেন?',
    disconnectTelegramDesc: 'আপনি টেলিগ্রামে লেনদেন পাবেন না।',
    disconnectBtn: 'সংযোগ বিচ্ছিন্ন',
    disconnectWhatsAppTitle: 'হোয়াটসঅ্যাপ সংযোগ বিচ্ছিন্ন করবেন?',
    disconnectWhatsAppDesc: 'আপনি হোয়াটসঅ্যাপে লেনদেন পাবেন না।',
    failedConnect: 'সংযোগ ব্যর্থ। আবার চেষ্টা করুন।',
    failedGenerateCode: 'সংযোগ কোড তৈরি করতে ব্যর্থ',
    whatsappConnectedSuccess: 'হোয়াটসঅ্যাপ সফলভাবে সংযুক্ত হয়েছে!',
    connectionTimedOut: 'সংযোগের সময় শেষ। আবার চেষ্টা করুন।',
    whatsappDisconnected: 'হোয়াটসঅ্যাপ সংযোগ বিচ্ছিন্ন হয়েছে',
    failedDisconnect: 'সংযোগ বিচ্ছিন্ন করতে ব্যর্থ। আবার চেষ্টা করুন।',

    // Notifications
    notificationsTitle: 'বিজ্ঞপ্তি',
    searchNotifications: 'বিজ্ঞপ্তি অনুসন্ধান...',
    unread: 'অপঠিত',
    markAllAsRead: 'সব পঠিত করুন',
    selectMessages: 'বার্তা নির্বাচন',
    selectAllNotifs: 'সব নির্বাচন',
    cancelSelection: 'নির্বাচন বাতিল',
    noMatchingNotifications: 'কোনো মিলে যাওয়া বিজ্ঞপ্তি নেই',
    noUnreadNotifications: 'কোনো অপঠিত বিজ্ঞপ্তি নেই',
    noNotificationsYet: 'এখনো কোনো বিজ্ঞপ্তি নেই',
    tryAdjustingSearch: 'আপনার অনুসন্ধান সামঞ্জস্য করে দেখুন',
    allCaughtUp: 'আপনি সব দেখেছেন!',
    notifyWhenSomethingHappens: 'কিছু ঘটলে আমরা আপনাকে জানাব।',
    clearSearch: 'অনুসন্ধান মুছুন',
    deselectAll: 'সব অনির্বাচন',
    xSelected: '{count}টি নির্বাচিত',
    markRead: 'পঠিত করুন',
    deleteXNotifs: 'মুছুন ({count})',
    notificationDeleted: 'বিজ্ঞপ্তি মুছে ফেলা হয়েছে',
    failedDeleteNotification: 'বিজ্ঞপ্তি মুছতে ব্যর্থ',
    allNotifsMarkedRead: 'সব বিজ্ঞপ্তি পঠিত করা হয়েছে',
    xNotifsDeleted: '{count}টি বিজ্ঞপ্তি মুছে ফেলা হয়েছে',
    failedDeleteSomeNotifs: 'কিছু বিজ্ঞপ্তি মুছতে ব্যর্থ',
    xNotifsMarkedRead: '{count}টি বিজ্ঞপ্তি পঠিত করা হয়েছে',
    loadMore: 'আরও লোড',
    loadingMore: 'লোড হচ্ছে...',

    // Privacy & Security
    privacySecurityTitle: 'গোপনীয়তা ও নিরাপত্তা',
    accountSecurity: 'অ্যাকাউন্ট নিরাপত্তা',
    changePassword: 'পাসওয়ার্ড পরিবর্তন',
    updateAccountPassword: 'আপনার অ্যাকাউন্টের পাসওয়ার্ড আপডেট করুন',
    currentPassword: 'বর্তমান পাসওয়ার্ড',
    enterCurrentPassword: 'বর্তমান পাসওয়ার্ড দিন',
    currentPasswordRequired: 'বর্তমান পাসওয়ার্ড প্রয়োজন',
    newPassword: 'নতুন পাসওয়ার্ড',
    minCharacters: 'ন্যূনতম ৮ অক্ষর',
    weak: 'দুর্বল', medium: 'মাঝারি', strong: 'শক্তিশালী',
    atLeast8Chars: 'কমপক্ষে ৮ অক্ষর',
    containsNumber: 'একটি সংখ্যা আছে',
    containsSpecialChar: 'একটি বিশেষ অক্ষর আছে (!@#$%^&*)',
    confirmNewPassword: 'নতুন পাসওয়ার্ড নিশ্চিত করুন',
    repeatNewPassword: 'নতুন পাসওয়ার্ড পুনরায় দিন',
    passwordsMatch: 'পাসওয়ার্ড মিলেছে',
    passwordsNoMatch: 'পাসওয়ার্ড মেলেনি',
    updatingEllipsis: 'আপডেট হচ্ছে...',
    passwordUpdated: 'পাসওয়ার্ড আপডেট হয়েছে!',
    updatePassword: 'পাসওয়ার্ড আপডেট',
    passwordUpdatedSuccess: 'পাসওয়ার্ড সফলভাবে আপডেট হয়েছে!',
    unableToVerifyAccount: 'আপনার অ্যাকাউন্ট যাচাই করা যায়নি। আবার লগ ইন করুন।',
    currentPasswordIncorrect: 'বর্তমান পাসওয়ার্ড ভুল।',
    dataAnalytics: 'ডেটা ও বিশ্লেষণ',
    analyticsCrashReports: 'বিশ্লেষণ ও ক্র্যাশ রিপোর্ট',
    shareAnonymousData: 'FinFlow উন্নত করতে বেনামী ব্যবহারের ডেটা শেয়ার করুন',
    neverSellData: 'আমরা কখনো আপনার ডেটা বিক্রি করি না। বিশ্লেষণ সম্পূর্ণ বেনামী এবং কোনো ব্যক্তিগত বা আর্থিক তথ্য অন্তর্ভুক্ত করে না।',

    // Backup & Restore
    backupRestoreTitle: 'ব্যাকআপ ও পুনরুদ্ধার',
    backupYourData: 'আপনার ডেটা ব্যাকআপ করুন',
    exportCopyForSafekeeping: 'সুরক্ষার জন্য আপনার ডেটার একটি কপি রপ্তানি করুন। নীচের পুনরুদ্ধার বিভাগ ব্যবহার করে যেকোনো সময় পুনরুদ্ধার করতে পারবেন।',
    exportingEllipsis: 'রপ্তানি হচ্ছে...',
    downloaded: 'ডাউনলোড হয়েছে!',
    exportCSVBtn: 'CSV রপ্তানি',
    txBudgetsAsSpreadsheet: 'স্প্রেডশিট হিসাবে লেনদেন ও বাজেট',
    exportJSONBtn: 'JSON রপ্তানি',
    txBudgetsAsJSON: 'JSON ফাইল হিসাবে লেনদেন ও বাজেট',
    restoreData: 'ডেটা পুনরুদ্ধার',
    importMayOverwrite: 'ডেটা আমদানি করলে আপনার বিদ্যমান রেকর্ড ওভাররাইট হতে পারে। প্রথমে ব্যাকআপ রপ্তানি করার পরামর্শ দেওয়া হচ্ছে।',
    dropBackupFile: 'আপনার ব্যাকআপ ফাইল এখানে ড্রপ করুন',
    supportsCSVJSON: '.csv এবং .json ফাইল সমর্থিত',
    browseFile: 'ফাইল ব্রাউজ',
    fileReadyToImport: 'আমদানির জন্য ফাইল প্রস্তুত',
    changeBtnLabel: 'পরিবর্তন',
    transactionsFound: 'লেনদেন পাওয়া গেছে',
    dateRange: 'তারিখ পরিসর',
    budgetsLabel: 'বাজেট',
    categoriesLabel: 'শ্রেণী',
    importMode: 'আমদানি মোড',
    merge: 'একত্রিত',
    addToExistingData: 'বিদ্যমান ডেটায় যোগ',
    replace: 'প্রতিস্থাপন',
    overwriteAllData: 'সব ডেটা ওভাররাইট',
    willDeleteCurrentData: 'এটি আপনার সমস্ত বর্তমান ডেটা মুছে ফেলবে',
    importingEllipsis: 'আমদানি হচ্ছে...',
    mergeImportData: 'একত্রিত ও আমদানি',
    replaceImportData: 'প্রতিস্থাপন ও আমদানি',
    noTxToExport: 'রপ্তানি করার কোনো লেনদেন নেই।',
    exportFailedTryAgain: 'রপ্তানি ব্যর্থ, আবার চেষ্টা করুন।',
    fileTooLarge: 'ফাইল বড়। সর্বোচ্চ আকার ৫MB।',
    onlyJsonCSVSupported: 'শুধু .json এবং .csv ফাইল সমর্থিত।',
    noValidDataInFile: 'ফাইলে কোনো বৈধ ডেটা পাওয়া যায়নি।',
    invalidFile: 'অবৈধ ফাইল। অনুগ্রহ করে FinFlow রপ্তানি ব্যবহার করুন।',
    dataImportedSuccess: 'ডেটা সফলভাবে আমদানি হয়েছে ({count}টি লেনদেন যোগ)',
    importFailed: 'আমদানি ব্যর্থ। আপনার ফাইলের ফরম্যাট পরীক্ষা করুন।',

    // Transaction Detail
    noteOptional: 'নোট (ঐচ্ছিক)',
    addANote: 'একটি নোট যোগ করুন...',
    timeLabel: 'সময়',
    noteLabel: 'নোট',

    // Add - ManualTab
    allCategories: 'সব শ্রেণী',
    morePlus: 'আরও +',
    whatWasThisFor: 'এটা কিসের জন্য? (ঐচ্ছিক)',
    savingTransaction: 'সংরক্ষণ হচ্ছে...',
    saveTransaction: 'লেনদেন সংরক্ষণ',
    pleaseEnterAmount: 'একটি পরিমাণ দিন',
    pleaseSelectCategory: 'একটি শ্রেণী নির্বাচন করুন',

    // Add - NLPTab
    xTransactionsFound: '{count}টি লেনদেন পাওয়া গেছে',
    discardAll: 'সব বাতিল',
    saveAllX: 'সব সংরক্ষণ ({count})',
    nlpPlaceholder: 'যেমন "২০০০ টাকা খাবারে এবং ২৯০ টাকা পরিবহনে খরচ"',
    parsingEllipsis: 'পার্সিং হচ্ছে...',
    parseWithAI: 'AI দিয়ে পার্স',
    failedToParse: 'পার্স ব্যর্থ। আবার চেষ্টা করুন।',

    // Add - VoiceTab
    voiceCaptured: 'ভয়েস ক্যাপচার হয়েছে',
    processingEllipsis: 'প্রক্রিয়াকরণ হচ্ছে...',
    listeningStatus: 'শুনছে...',
    tapToSpeakStatus: 'বলতে ট্যাপ করুন',
    voiceLanguages: 'হিন্দি · বাংলা · তামিল · তেলুগু ও আরও',
    micAccessDenied: 'মাইক্রোফোন অ্যাক্সেস অস্বীকৃত। অনুগ্রহ করে অনুমতি দিন এবং আবার চেষ্টা করুন।',
    couldNotCatch: 'শোনা যায়নি। ট্যাপ করে আবার চেষ্টা করুন।',
    transcriptLabel: 'ট্রান্সক্রিপ্ট:',

    // Add - ScanTab
    readingImage: 'ছবি পড়া হচ্ছে...',
    extractingText: 'টেক্স্ট বের করা হচ্ছে...',
    parsingDetails: 'বিস্তারিত পার্স হচ্ছে...',
    doneLabel: 'সম্পন্ন!',
    openCamera: 'ক্যামেরা খুলুন',
    uploadFromGallery: 'গ্যালারি থেকে আপলোড',
    jpgPngPdfSupported: 'JPG, PNG, PDF সমর্থিত',
    scanningEllipsis: 'স্ক্যান হচ্ছে...',
    failedToScan: 'রসিদ স্ক্যান ব্যর্থ',

    // PreviewCard
    aiUnderstoodAs: 'AI এভাবে বুঝেছে:',
    aiConfidence: 'AI আত্মবিশ্বাস',
    pleaseVerifyDetails: 'বিস্তারিত যাচাই করুন',
    confirmSave: 'সংরক্ষণ নিশ্চিত',

    // Layout
    addBtn: 'যোগ',
    viewProfile: 'প্রোফাইল দেখুন',
    editProfile: 'প্রোফাইল সম্পাদনা',
    signOutBtn: 'সাইন আউট',
    printedOn: '{date} তারিখে প্রিন্ট',

    // NotificationCenter
    notifHeader: 'বিজ্ঞপ্তি',
    noNotifsYet: 'এখনো কোনো বিজ্ঞপ্তি নেই',
    markAllRead: 'সব পঠিত করুন',
    viewAllNotifs: 'সব দেখুন',

    // InstallPrompt
    installPromptTitle: 'FinFlow ইনস্টল করুন',
    tapShareAddToHome: 'শেয়ার ট্যাপ করে "হোম স্ক্রিনে যোগ করুন" নির্বাচন করুন',
    addToHomeQuickAccess: 'দ্রুত অ্যাক্সেসের জন্য হোম স্ক্রিনে যোগ করুন',
    installPromptBtn: 'ইনস্টল',
  },
};

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType>({
  language: 'en',
  setLanguage: () => {},
  t: (key) => key,
});

export const useLanguage = () => useContext(LanguageContext);

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguageState] = useState<Language>(() => {
    if (typeof window === 'undefined') return 'en';
    return (localStorage.getItem('finflow_language') as Language) || 'en';
  });

  const setLanguage = (lang: Language) => {
    setLanguageState(lang);
    localStorage.setItem('finflow_language', lang);
  };

  const t = (key: string) => translations[language][key] || key;

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}
