import type { Metadata } from 'next'
import Link from 'next/link'

export const metadata: Metadata = {
  title: 'FinFlow | Disclaimer',
}

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-16">
      <div className="mb-12">
        <h1 className="text-3xl sm:text-4xl font-bold text-neutral-900 mb-4">
          Disclaimer
        </h1>
        <p className="text-neutral-600">
          Effective Date: March 1, 2026
        </p>
      </div>

      <div className="prose prose-neutral max-w-none">
        <p className="text-lg text-neutral-700 leading-relaxed mb-8">
          Please read this disclaimer carefully before using FinFlow. By using our service, 
          you acknowledge and agree to the limitations and conditions outlined below.
        </p>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-neutral-900 mb-4">
            Not Financial Advice
          </h2>
          <p className="text-neutral-700 leading-relaxed">
            FinFlow is a personal finance tracking tool and is not a financial advisory service. 
            Any insights, reports, summaries, or suggestions provided by FinFlow are for 
            informational purposes only and should not be construed as professional financial 
            advice. We are not financial advisors, and nothing in our service should be 
            interpreted as a recommendation to buy, sell, or hold any financial product or 
            to pursue any particular financial strategy.
          </p>
          <p className="text-neutral-700 leading-relaxed mt-4">
            Before making any financial decisions, you should consult with a qualified 
            financial advisor who can consider your individual circumstances, objectives, 
            and risk tolerance. Your financial situation is unique, and any decisions 
            regarding your money should be made with appropriate professional guidance.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-neutral-900 mb-4">
            AI Accuracy
          </h2>
          <p className="text-neutral-700 leading-relaxed">
            FinFlow utilizes artificial intelligence to provide features such as receipt 
            scanning, voice transcription, transaction categorization, and financial insights. 
            While we continuously work to improve the accuracy of our AI systems, we cannot 
            guarantee that AI-generated content will always be accurate, complete, or reliable.
          </p>
          <p className="text-neutral-700 leading-relaxed mt-4">
            AI systems can make mistakes, misinterpret data, or produce results that do not 
            accurately reflect your financial situation. You are solely responsible for 
            reviewing, verifying, and correcting any information processed or generated by 
            our AI features. Never rely solely on AI-generated insights for important 
            financial decisions without independent verification.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-neutral-900 mb-4">
            Data Accuracy
          </h2>
          <p className="text-neutral-700 leading-relaxed">
            The accuracy of the information in FinFlow depends entirely on the accuracy of 
            the data you enter. We do not verify the accuracy of your transaction details, 
            account balances, or other financial information you input. Any errors in your 
            data entry will affect the accuracy of reports, insights, and summaries generated 
            by FinFlow.
          </p>
          <p className="text-neutral-700 leading-relaxed mt-4">
            You are responsible for ensuring that all information entered into FinFlow is 
            accurate and up to date. We recommend regularly reviewing your data and reconciling 
            it with your actual financial records to maintain accuracy.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-neutral-900 mb-4">
            Availability
          </h2>
          <p className="text-neutral-700 leading-relaxed">
            We strive to keep FinFlow available and functioning at all times, but we cannot 
            guarantee uninterrupted access to our service. Technical issues, maintenance, 
            updates, or circumstances beyond our control may result in temporary downtime 
            or service disruptions. We are not liable for any loss or inconvenience caused 
            by such interruptions.
          </p>
          <p className="text-neutral-700 leading-relaxed mt-4">
            We recommend regularly exporting and backing up your financial data to ensure 
            you maintain access to your records even if service interruptions occur. Your 
            data is your responsibility, and maintaining backups is an important part of 
            using any financial tracking tool.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-neutral-900 mb-4">
            No Warranty
          </h2>
          <p className="text-neutral-700 leading-relaxed">
            FinFlow is provided on an as-is and as-available basis without any warranties 
            of any kind, whether express or implied. We do not warrant that the service 
            will meet your requirements, be error-free, secure, or free from viruses or 
            other harmful components. Your use of FinFlow is at your own risk.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-neutral-900 mb-4">
            Contact
          </h2>
          <p className="text-neutral-700 leading-relaxed">
            If you have any questions about this disclaimer, please contact us at{' '}
            <a
              href="mailto:contact@sadabmunshi.online"
              className="text-neutral-900 underline hover:no-underline"
            >
              contact@sadabmunshi.online
            </a>
            .
          </p>
        </section>
      </div>

      <div className="mt-12 pt-8 border-t border-neutral-100">
        <Link
          href="/"
          className="text-neutral-600 hover:text-neutral-900 transition-colors"
        >
          Back to Home
        </Link>
      </div>
    </div>
  )
}
