import type { Metadata } from 'next'
import BackButton from '@/components/landing/BackButton'

export const metadata: Metadata = {
  title: 'FinFlow | Disclaimer',
}

export default function DisclaimerPage() {
  return (
    <div className="max-w-3xl mx-auto px-4 sm:px-6 lg:px-8 py-10 sm:py-16">

      {/* ── back button ── */}
      <BackButton />

      <div className="mb-12">
        <h1 className="text-3xl sm:text-4xl font-bold text-neutral-900 mb-4">
          Disclaimer
        </h1>
        <p className="text-neutral-600">
          Effective Date: March 26, 2026
        </p>
      </div>

      <div className="prose prose-neutral max-w-none">
        <p className="text-lg text-neutral-700 leading-relaxed mb-8">
          Please read this disclaimer carefully before using FinFlow. By using our service, 
          you acknowledge and agree to the limitations and conditions outlined below.
        </p>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-neutral-900 mb-4">
            Not Financial Advice
          </h2>
          <p className="text-neutral-700 leading-relaxed">
            FinFlow is a personal finance tracking tool — not a financial advisory service. 
            Any insights, reports, summaries, or suggestions generated by FinFlow are for 
            informational purposes only and must not be construed as professional financial, 
            tax, or investment advice. We are not licensed financial advisors, and nothing 
            within the service should be interpreted as a recommendation to buy, sell, or 
            hold any financial product, or to pursue any particular financial strategy.
          </p>
          <p className="text-neutral-700 leading-relaxed mt-4">
            Before making any financial decisions, consult a qualified financial advisor who 
            can consider your individual circumstances, objectives, and risk tolerance.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-neutral-900 mb-4">
            AI Accuracy
          </h2>
          <p className="text-neutral-700 leading-relaxed">
            FinFlow uses artificial intelligence to power features such as receipt scanning, 
            voice transcription, transaction categorisation, and financial insights. While we 
            continuously work to improve accuracy, we cannot guarantee that AI-generated 
            content will always be accurate, complete, or reliable.
          </p>
          <p className="text-neutral-700 leading-relaxed mt-4">
            AI systems may misinterpret data or produce results that do not accurately reflect 
            your financial situation. You are solely responsible for reviewing, verifying, and 
            correcting any AI-processed information. Never rely exclusively on AI-generated 
            insights for important financial decisions without independent verification.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-neutral-900 mb-4">
            Data Accuracy
          </h2>
          <p className="text-neutral-700 leading-relaxed">
            The accuracy of information within FinFlow depends entirely on the data you provide. 
            We do not independently verify the accuracy of your transaction details, account 
            balances, or other financial information. Any errors in data entry will propagate 
            to reports, insights, and summaries.
          </p>
          <p className="text-neutral-700 leading-relaxed mt-4">
            You are responsible for ensuring that all information entered into FinFlow is 
            accurate and current. We recommend periodically reconciling your FinFlow records 
            against your actual bank statements and financial documents.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-neutral-900 mb-4">
            Service Availability
          </h2>
          <p className="text-neutral-700 leading-relaxed">
            We strive to keep FinFlow available at all times, but we cannot guarantee 
            uninterrupted access. Technical issues, scheduled maintenance, updates, or 
            circumstances beyond our control may result in temporary downtime or service 
            disruptions. We are not liable for any loss or inconvenience caused by such 
            interruptions.
          </p>
          <p className="text-neutral-700 leading-relaxed mt-4">
            We recommend regularly exporting your financial data using the built-in export 
            tools to maintain an independent backup of your records.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-neutral-900 mb-4">
            Third-Party Integrations
          </h2>
          <p className="text-neutral-700 leading-relaxed">
            FinFlow integrates with third-party platforms such as WhatsApp and Telegram for 
            optional bot-based access. We do not control these platforms and are not 
            responsible for their availability, security policies, or terms of service. Your 
            use of these integrations is subject to the respective platform&rsquo;s own terms 
            and privacy policies.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-neutral-900 mb-4">
            No Warranty
          </h2>
          <p className="text-neutral-700 leading-relaxed">
            FinFlow is provided on an &ldquo;as-is&rdquo; and &ldquo;as-available&rdquo; basis 
            without warranties of any kind, whether express or implied. We do not warrant that 
            the service will meet your specific requirements, be error-free, secure, or free 
            from viruses or other harmful components. Your use of FinFlow is at your own risk.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-neutral-900 mb-4">
            Limitation of Liability
          </h2>
          <p className="text-neutral-700 leading-relaxed">
            To the maximum extent permitted by applicable law, FinFlow and its creators shall 
            not be liable for any indirect, incidental, special, consequential, or punitive 
            damages arising out of or in connection with your use of the service, including 
            but not limited to loss of profits, data, goodwill, or other intangible losses.
          </p>
        </section>

        <section className="mb-10">
          <h2 className="text-xl font-semibold text-neutral-900 mb-4">
            Contact
          </h2>
          <p className="text-neutral-700 leading-relaxed">
            If you have any questions about this disclaimer, please contact us at{' '}
            <a
              href="mailto:contact@sadabmunshi.online"
              className="text-neutral-900 underline hover:no-underline"
            >
              contact@sadabmunshi.online
            </a>
            .
          </p>
        </section>
      </div>

      <div className="mt-12 pt-8 border-t border-neutral-100">
        <BackButton />
      </div>
    </div>
  )
}
